### ISSUE TITLE
info

### ISSUE THREAD

**Issue by clark-john** [ChaanBiz/Creative_#1]
frontend lang yung kayang i-deploy ng github pages, so expected na di gagana yung backend.
comment *agree* if you are aware of it.

**Comment by ChaanBiz** [comment]
Agree. Afternoon, I see. Thank you for informating me.Sent from my Huawei phone-------- Original message --------From: Clark ***@***.***>Date: Sat, 29 Oct 2022, 10:48 amTo: ChaanBiz/Creative_ ***@***.***>Cc: Subscribed ***@***.***>Subject: [ChaanBiz/Creative_] info (Issue #1)
frontend lang yung kayang i-deploy ng github pages, so expected na di gagana yung backend.
comment agree if you are aware of it.
